Repository CPS-IT/project-builder, pull requests merged in 2022-12, with the labels that each got.

#47 [!!!][FEATURE] Upgrade to `cuyz/valinor` 1.0.0
  composer.json
  composer.lock
  src/Error/ErrorHandler.php
Labels: enhancement, breaking

#24 [FEATURE] Add support for PHP 8.2
  .github/workflows/tests.yaml
  composer.json
  composer.lock
  installer/composer.json.twig
  tests/src/Fixtures/Templates/json-template/composer.json
  tests/src/Fixtures/Templates/yaml-template/composer.json
Labels: enhancement

#48 [BUGFIX] Satisfy PHP extension requirements in Dockerfile
  Dockerfile
Labels: bug

#49 [TASK] Upgrade to Composer 2.4 in Dockerfile
  Dockerfile
Labels: maintenance

#52 [BUGFIX] Fall back to dot-zero release if PHP version cannot be determined
  src/Resource/Http/PhpApiClient.php
  tests/src/Resource/Http/PhpApiClientTest.php
Labels: bug

#55 [FEATURE] Measure type coverage within PHPStan
  composer.json
  composer.lock
  phpstan.neon
  src/IO/InputReader.php
Labels: enhancement

#54 [FEATURE] Introduce target file support for processed source files
  resources/config.schema.json
  src/Builder/Config/ValueObject/FileCondition.php
  src/Builder/Generator/Step/ProcessSharedSourceFilesStep.php
  src/Builder/Generator/Step/ProcessSourceFilesStep.php
  src/Builder/Generator/Step/ProcessingFilesTrait.php
  src/Builder/Writer/GenericFileWriter.php
  src/Builder/Writer/TemplateWriter.php
  src/Builder/Writer/WriterInterface.php
  tests/src/Builder/Config/ConfigFactoryTest.php
  tests/src/Builder/Config/ValueObject/FileConditionTest.php
  tests/src/Builder/Generator/Step/ProcessSharedSourceFilesStepTest.php
  tests/src/Builder/Generator/Step/ProcessSourceFilesStepTest.php
  tests/src/Builder/Writer/GenericFileWriterTest.php
  tests/src/Builder/Writer/TemplateWriterTest.php
  tests/src/Fixtures/Templates/json-template/config.json
  tests/src/Fixtures/Templates/json-template/templates/shared/shared-dummy/templates/src/shared-dummy-2.json
  tests/src/Fixtures/Templates/json-template/templates/shared/shared-dummy/templates/src/shared-dummy-3.json
  tests/src/Fixtures/Templates/json-template/templates/shared/shared-dummy/templates/src/shared-dummy-4.json
  tests/src/Fixtures/Templates/json-template/templates/shared/shared-dummy/templates/src/shared-dummy.json.twig
  tests/src/Fixtures/Templates/json-template/templates/shared/shared-dummy/templates/src/shared-dummy.yaml.twig
  tests/src/Fixtures/Templates/json-template/templates/src/dummy-4.json
  tests/src/Fixtures/Templates/yaml-template/config.yaml
  tests/src/Fixtures/Templates/yaml-template/templates/shared/shared-dummy/templates/src/shared-dummy-4.yaml
  tests/src/Fixtures/Templates/yaml-template/templates/src/dummy-4.yaml
Labels: enhancement

#59 [BUGFIX] Exit early if current environment is unsupported
  src/Bootstrap.php
  src/Exception/UnsupportedEnvironmentException.php
Labels: bug

#61 [FEATURE] Allow specifying template package version constraint
  installer/composer.json.twig
  src/Exception/InvalidTemplateSourceException.php
  src/Template/Provider/BaseComposerProvider.php
  src/Template/TemplateSource.php
  tests/src/Template/Provider/BaseComposerProviderTest.php
Labels: enhancement

#64 [BUGFIX] Streamline usage of project root paths
  src/Builder/Config/ConfigFactory.php
  src/Builder/Config/ConfigReader.php
Labels: bug

#67 [BUGFIX] Use Dependabot's automatic versioning strategy
  .github/dependabot.yml
Labels: bug

#65 [TASK] Decouple application logic from bootstrapping
  config/services.yaml
  docs/architecture.md
  src/Bootstrap.php
  src/Console/Application.php
  src/Console/Simulation.php
  tests/src/ClearableBufferIO.php
  tests/src/Console/ApplicationTest.php
  tests/src/ContainerAwareTestCase.php
  tests/src/Fixtures/DummyProvider.php
Labels: maintenance

#60 [FEATURE] Set Packagist as default provider and auto-fetch template sources
  src/Console/Application.php
  src/Exception/InvalidTemplateSourceException.php
  src/IO/Messenger.php
  src/Template/Provider/BaseComposerProvider.php
  src/Template/Provider/CustomComposerProvider.php
  src/Template/Provider/PackagistProvider.php
  src/Template/Provider/ProviderInterface.php
  tests/src/Console/ApplicationTest.php
  tests/src/Fixtures/DummyComposerProvider.php
  tests/src/Fixtures/DummyProvider.php
Labels: enhancement

#68 [BUGFIX] Properly handle latest version constraint
  installer/composer.json.twig
  src/Template/Provider/BaseComposerProvider.php
  src/Template/TemplateSource.php
  tests/src/Template/Provider/BaseComposerProviderTest.php
  tests/src/Template/TemplateSourceTest.php
Labels: bug

#69 [BUGFIX] Allow using constraints with minimum stability "dev"
  installer/composer.json.twig
Labels: bug

#71 [TASK] Retire ChangeLog
  ChangeLog
Labels: maintenance

#66 [TASK] Include Composer 2.5 in test matrix
  .github/workflows/tests.yaml
Labels: maintenance
