Repository CPS-IT/project-builder, pull requests merged in 2022-11, with the labels that each got.

#39 [TASK] Make codebase compatible with PHPStan 1.9.x
  composer.json
  composer.lock
  src/Builder/Config/ValueObject/ConditionTrait.php
  src/Builder/Generator/Step/Interaction/QuestionInteraction.php
  src/Builder/Generator/Step/Interaction/SelectInteraction.php
  src/IO/InputReader.php
  src/Twig/Func/ResolveIpFunction.php
Labels: maintenance

#38 [TASK] Enable Dependabot auto-merge for minor and patch updates
  .github/workflows/auto-merge.yaml
Labels: maintenance

#40 [FEATURE] Add support for cuyz/valinor 0.15.x and 0.16.x
  composer.json
  composer.lock
Labels: enhancement

#41 [FEATURE] Add support for conditional properties
  resources/config.schema.json
  src/Builder/Config/ValueObject/Property.php
  src/Builder/Generator/Step/CollectBuildInstructionsStep.php
  tests/src/Builder/Config/ConfigFactoryTest.php
  tests/src/Builder/Config/ValueObject/PropertyTest.php
  tests/src/ContainerAwareTestCase.php
  tests/src/Fixtures/Templates/json-template/config.json
  tests/src/Fixtures/Templates/yaml-template/config.yaml
Labels: enhancement

#42 [BUGFIX] Replace Dependabot auto-merge action
  .github/workflows/auto-merge.yaml
Labels: bug

#36 [!!!][FEATURE] Introduce dynamic providers for template packages
  .github/workflows/cgl.yaml
  .github/workflows/tests.yaml
  Dockerfile
  composer.json
  composer.lock
  composer.templates.json
  config/services.yaml
  docs/configuration.md
  installer/composer.json.twig
  src/Bootstrap.php
  src/Builder/Config/ConfigReader.php
  src/Exception/InvalidResourceException.php
  src/Exception/InvalidTemplateSourceException.php
  src/IO/InputReader.php
  src/IO/Messenger.php
  src/Paths.php
  src/Resource/Local/Composer.php
  src/Template/Provider/BaseComposerProvider.php
  src/Template/Provider/CustomComposerProvider.php
  src/Template/Provider/CustomProviderInterface.php
  src/Template/Provider/PackagistProvider.php
  src/Template/Provider/ProviderInterface.php
  src/Template/TemplateSource.php
  src/Twig/Renderer.php
  tests/src/Builder/Config/ConfigReaderTest.php
  tests/src/Fixtures/DummyComposerProvider.php
  tests/src/Fixtures/DummyProvider.php
  tests/src/IO/MessengerTest.php
  tests/src/Template/Provider/BaseComposerProviderTest.php
  tests/src/Template/Provider/CustomComposerProviderTest.php
  tests/src/Template/TemplateSourceTest.php
Labels: enhancement, breaking

#35 [!!!][FEATURE] Streamline template structure of shared packages
  docs/configuration.md
  src/Builder/Generator/Step/ProcessSharedSourceFilesStep.php
  tests/src/Fixtures/Templates/json-template/templates/shared/shared-dummy/templates/src/shared-dummy-2.yaml
  tests/src/Fixtures/Templates/json-template/templates/shared/shared-dummy/templates/src/shared-dummy-3.yaml
  tests/src/Fixtures/Templates/json-template/templates/shared/shared-dummy/templates/src/shared-dummy.yaml.twig
  tests/src/Fixtures/Templates/yaml-template/templates/shared/shared-dummy/templates/src/shared-dummy-2.yaml
  tests/src/Fixtures/Templates/yaml-template/templates/shared/shared-dummy/templates/src/shared-dummy-3.yaml
  tests/src/Fixtures/Templates/yaml-template/templates/shared/shared-dummy/templates/src/shared-dummy.yaml.twig
Labels: enhancement, breaking

#44 [TASK] Use PHPStan extension installer
  composer.json
  composer.lock
  phpstan.neon
  src/Resource/Local/Composer.php
  tests/src/Twig/Func/PhpVersionFunctionTest.php
Labels: maintenance

#45 [TASK] Add Rector for automatic code migration
  .gitattributes
  .github/workflows/cgl.yaml
  composer.json
  composer.lock
  rector.php
  src/Builder/BuildResult.php
  tests/src/Resource/Local/ProcessedFileTest.php
Labels: maintenance
