Repository CPS-IT/project-builder, pull requests merged in 2023-04, with the labels that each got.

#163 [DOCS] Improve SEO by providing relevant OpenGraph tags
  docs/conf.py
  docs/index.md
Labels: documentation

#170 [FEATURE] Support templated target directories
  docs/development/configuration.md
  rector.php
  resources/config.schema.json
  src/Builder/Generator/Step/MirrorProcessedFilesStep.php
  src/Builder/Generator/Step/ProcessSharedSourceFilesStep.php
  src/Builder/Generator/Step/ProcessSourceFilesStep.php
  src/Builder/Generator/Step/ProcessingFilesTrait.php
  tests/src/Builder/Config/ConfigFactoryTest.php
  tests/src/Builder/Generator/Step/ProcessSharedSourceFilesStepTest.php
  tests/src/Builder/Generator/Step/ProcessSourceFilesStepTest.php
  tests/src/Fixtures/Files/invalid-config-file-condition-path.yaml
  tests/src/Fixtures/Files/invalid-config-file-condition-target.yaml
  tests/src/Fixtures/Files/invalid-config-file.yaml
  tests/src/Fixtures/Templates/json-template/config.json
  tests/src/Fixtures/Templates/json-template/templates/shared/shared-dummy/templates/src/shared-dummy/shared-dummy-1.json
  tests/src/Fixtures/Templates/json-template/templates/shared/shared-dummy/templates/src/shared-dummy/shared-dummy-2.json
  tests/src/Fixtures/Templates/json-template/templates/src/dummy/dummy-1.json
  tests/src/Fixtures/Templates/json-template/templates/src/dummy/dummy-2.json
  tests/src/Fixtures/Templates/yaml-template/config.yaml
  tests/src/Fixtures/Templates/yaml-template/templates/shared/shared-dummy/templates/src/shared-dummy/shared-dummy-1.yaml
  tests/src/Fixtures/Templates/yaml-template/templates/shared/shared-dummy/templates/src/shared-dummy/shared-dummy-2.yaml
  tests/src/Fixtures/Templates/yaml-template/templates/src/dummy/dummy-1.yaml
  tests/src/Fixtures/Templates/yaml-template/templates/src/dummy/dummy-2.yaml
Labels: enhancement

#171 [FEATURE] Loosen requirement for "if" condition if "target" is set
  docs/development/configuration.md
  resources/config.schema.json
  src/Builder/Config/ValueObject/FileCondition.php
  tests/src/Builder/Config/ConfigFactoryTest.php
  tests/src/Fixtures/Templates/json-template/config.json
  tests/src/Fixtures/Templates/yaml-template/config.yaml
Labels: enhancement

#186 [BUGFIX] Properly handle no selection for optional multi-select fields
  src/IO/InputReader.php
  tests/src/IO/InputReaderTest.php
Labels: bug
