Repository CPS-IT/project-builder, pull requests merged in 2023-03, with the labels that each got.

#122 [FEATURE] Show resolved template version in install progress
  composer.json
  composer.lock
  src/IO/Messenger.php
  src/Template/Provider/BaseProvider.php
  tests/src/Template/Provider/BaseProviderTest.php
Labels: enhancement

#123 [DOCS] Update documentation url
  CONTRIBUTING.md
  README.md
  docs/conf.py
Labels: documentation

#131 [TASK] Remove PHP_CS_FIXER_IGNORE_ENV compatibility flag
  .github/workflows/cgl.yaml
Labels: maintenance

#132 [BUGFIX] Move `nyholm/psr7` package to dev-dependencies
  composer.json
  composer.lock
Labels: bug

#133 [TASK] Revert "Move unused package nyholm/psr7 to dev-dependencies"
  composer.json
  composer.lock
Labels: maintenance

#134 [BUGFIX] Improve type-safety of utility methods in ArrayHelper
  src/Helper/ArrayHelper.php
  tests/src/Helper/ArrayHelperTest.php
Labels: bug

#145 [TASK] Allow $schema property in config files
  resources/config.schema.json
  src/Builder/Config/ConfigFactory.php
  tests/src/Fixtures/Templates/json-template/config.json
  tests/src/Fixtures/Templates/yaml-template/config.yaml
Labels: maintenance

#154 [FEATURE] Introduce RegexValidator
  docs/development/architecture/components.md
  resources/config.schema.json
  src/IO/Validator/RegexValidator.php
  tests/src/IO/Validator/RegexValidatorTest.php
  tests/src/IO/Validator/ValidatorFactoryTest.php
Labels: enhancement

#155 [DOCS] Add example for newly added `RegexValidator`
  docs/development/configuration.md
Labels: documentation
