Repository CPS-IT/project-builder, pull requests merged in 2023-07, with the labels that each got.

#228 [FEATURE] Add new `runCommand` step
  composer.json
  composer.lock
  docs/development/build-steps.md
  docs/development/configuration.md
  resources/config.schema.json
  src/Builder/Config/ValueObject/StepOptions.php
  src/Builder/Generator/Step/RunCommandStep.php
  src/IO/Messenger.php
  tests/src/Builder/Config/ConfigFactoryTest.php
  tests/src/Builder/Config/ValueObject/StepOptionsTest.php
  tests/src/Builder/Generator/GeneratorTest.php
  tests/src/Builder/Generator/Step/RunCommandStepTest.php
  tests/src/Fixtures/Templates/json-template/config.json
  tests/src/Fixtures/Templates/yaml-template/config.yaml
  tests/src/IO/MessengerTest.php
Labels: enhancement

#250 [FEATURE] Allow to skip confirmation to run configured command
  docs/development/build-steps.md
  docs/development/configuration.md
  resources/config.schema.json
  src/Builder/Config/ValueObject/StepOptions.php
  src/Builder/Generator/Step/RunCommandStep.php
  tests/src/Builder/Config/ConfigFactoryTest.php
  tests/src/Builder/Generator/GeneratorTest.php
  tests/src/Builder/Generator/Step/RunCommandStepTest.php
  tests/src/Fixtures/Templates/json-template/config.json
  tests/src/Fixtures/Templates/yaml-template/config.yaml
Labels: enhancement

#251 [FEATURE] Use timestamps for build artifact versions
  config/services.yaml
  resources/build-artifact.schema.json
  src/Builder/Artifact/Migration/Migration.php
  src/Builder/Artifact/Migration/Migration1679497137.php
  src/Builder/ArtifactGenerator.php
  src/Builder/ArtifactReader.php
  tests/src/Fixtures/DummyMigration.php
Labels: enhancement

#95 [!!!][TASK] Lock provider type in template artifact
  resources/build-artifact.schema.json
  src/Builder/Artifact/Migration/Migration1688738958.php
  src/Builder/Artifact/TemplateArtifact.php
  src/Builder/ArtifactGenerator.php
  tests/src/Builder/Artifact/ArtifactTest.php
  tests/src/Builder/Artifact/Migration/Migration1688738958Test.php
  tests/src/Builder/Artifact/TemplateArtifactTest.php
  tests/src/Builder/ArtifactGeneratorTest.php
Labels: breaking, maintenance

#267 [BUGFIX] Write build artifact to target directory
  src/Builder/Generator/Step/GenerateBuildArtifactStep.php
  tests/src/Builder/Generator/GeneratorTest.php
  tests/src/Builder/Generator/Step/GenerateBuildArtifactStepTest.php
Labels: bug

#268 [FEATURE] Support expression languages providers for autoconfiguration
  config/services.php
  docs/development/configuration.md
  docs/development/dependency-injection.md
  rector.php
  src/DependencyInjection/CompilerPass/ExpressionLanguageProviderPass.php
Labels: enhancement

#269 [FEATURE] Render main property value as Twig template
  docs/development/configuration.md
  src/Builder/Generator/Step/CollectBuildInstructionsStep.php
  tests/src/Builder/Generator/Step/CollectBuildInstructionsStepTest.php
Labels: enhancement
