Repository CPS-IT/project-builder, pull requests merged in 2024-02, with the labels that each got.

#473 [FEATURE] Support exclusion of template packages
  docs/development/configuration.md
  src/Template/Provider/BaseProvider.php
  tests/src/Template/Provider/BaseProviderTest.php
Labels: enhancement

#461 [FEATURE] Demote abandoned packages in template list
  src/IO/Messenger.php
  src/Template/Provider/BaseProvider.php
  tests/src/IO/MessengerTest.php
  tests/src/Template/Provider/BaseProviderTest.php
Labels: enhancement

#477 [BUGFIX] Ignore "exclude-from-listing" config in VCS provider
  src/Template/Provider/VcsProvider.php
  tests/src/Template/Provider/VcsProviderTest.php
Labels: bug

#478 [TASK] Disable Composer cache while searching for template packages
  src/Template/Provider/BaseProvider.php
  tests/src/Template/Provider/BaseProviderTest.php
  tests/src/Template/Provider/VcsProviderTest.php
Labels: maintenance

#481 [TASK] Use composer/composer for Docker multi-stage build
  Dockerfile
Labels: maintenance

#475 [FEATURE] Add support for Composer 2.7
  .github/workflows/tests.yaml
  Dockerfile
Labels: enhancement

#486 [BUGFIX] Fix outdated link to documentation
  src/IO/Messenger.php
Labels: bug

#484 [BUGFIX] Disable template source cache for simulations only
  src/Bootstrap.php
  src/Console/Application.php
  src/Template/Provider/BaseProvider.php
  src/Template/Provider/VcsProvider.php
  tests/src/Template/Provider/BaseProviderTest.php
Labels: bug

#485 [TASK] Show exception details on failure with verbose output
  src/Builder/Generator/Generator.php
  tests/src/Builder/Generator/GeneratorTest.php
Labels: maintenance
